### PR TITLE
modified login page

### PR DESCRIPTION
**Pull request by Phionanamugga**
what does this PR do?
It does does not allow users login before providing all necessary details
@BrunoNicholas, @ringtho,@brucenelm,@kalsmic,@llwasampijja,@muleronald pliz review my pull request and advice on how I can improve my login page

### CODE REVIEW

**Comment by kalsmic** [comment]
You can also add a link to your user stories on  pivotal tracker and also one to the  Live project on gh-pages

**Comment by kalsmic** [comment]
I also happened to look at other files not worked on in this pull request. Please add a username field on the signup page

**Comment by Phionanamugga** [comment]
ok thanks

**Comment by llwasampijja** [comment]
You have than a great job @phionanamugga. The most of your site is responsive, you have wonderful features such as the chat, notifications etc. The signup page isn't responsive well. At certain screen sizes, it presents a horizontal scroll bar. Also, the navigation bar seems to not respond well. The items flow to the left and at one point the search bar is above the logout link, I think it would be better if the search bar is below the whole navigation menu. Also on those small screens, I think a vertical navigation bar looks better.
Great job

**Pull request merged**
